<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRxwFO8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRxwFO8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWRxwFO8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWRxwFO8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWRxwFO8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WRxwFO8',
    'container.build_id' => 'd656d7e5',
    'container.build_time' => 1528864737,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRxwFO8');
